---

- name: restart httpd server 
  service: 
    name: httpd
    enabled: yes
    state: restarted
  become: yes

- name: restart network
  service: 
    name: network
    state: restarted
    enabled: yes
  become: yes